version: "3"

services:
  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  django:
    build: ./api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./api:/app/api
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - app_net
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    networks:
      - app_net
    expose:
      - "3000"
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:

networks:
  app_net:
    name: "network"
    external: true
